### ISSUE TITLE
Add borg backup?

### ISSUE THREAD

**Issue by cpfeiffer** [mafredri/asustor-packages#1]
Would you be willing to package https://github.com/borgbackup/borg/?

Having it running on ADM would allow creating backups on the NAS via ssh without having to mess with sshfs mounts on the machine to be backed up.

**Comment by mafredri** [comment]
Hey @cpfeiffer. Are you still interested in this? If so I could probably take a look at it in the coming weeks.

**Comment by cpfeiffer** [comment]
Yes, indeed I'm still interested in this, much appreciated! :ok_hand:

**Comment by cpfeiffer** [comment]
I still am, FWIW ;-)

**Comment by pojanisu** [comment]
I just found out about borg and having it running on our NAS would be really great. So I'm also interested in testing this.

**Comment by mafredri** [comment]
Hey, apologies for the silence (and false hope).

I've grown a bit tired of the ADM operating system and am considering replacing it with Debian. For this reason I won't be taking on this app now. It would not make sense as I'm unlikely to be providing updates or support in future.

Sorry, and let's hope someone else can take it on.
